name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-devops-app:latest .

      - name: Save Docker image
        run: docker save my-devops-app:latest | gzip > app.tar.gz

      - name: Copy image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: app.tar.gz
          target: ~/

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < ~/app.tar.gz
            docker stop my-devops-app || true
            docker rm my-devops-app || true
            docker run -d \
              --name my-devops-app \
              --restart unless-stopped \
              -p 3000:3000 \
              my-devops-app:latest
            docker ps | grep my-devops-app
